### ISSUE TITLE
[POLL] Use one branch?

### ISSUE THREAD

**Issue by pvinis** [pvinis/rn-diff-purge#15]
I have the idea of merging the `master` and `project` branches.

Now, with these two branches, the project and all the tags are in one branch, and the docs are in another.
Pros:
- Easy to make diffs, as there is nothing else in the `project` branch besides the actual project.
Cons:
- No easy way to make PRs, since we need two PRs, one per branch, to make a new version.
(Solution: My bot runs the `new-version` script so it updates both branches automatically.)

The other possibility is to have a directory for the project, and the docs in the root dir, all in the same branch.
Pros:
- Easier PR, greenkeeper et al. or users could make an actual useful PR without messing with multi-PR setups.
Cons:
- The diffs are now not clean, since other things change besides the project code. A possible solution might be to somehow get a diff of only a dir in the repo(?).

If you are interested, have experience or an opinion, please comment here.  
You can also vote:  🎉 for two branches, 🚀 for one branch.

**Comment by mikehardy** [comment]
If you already have to use a script to automate diffs, it seems like moving to a single branch would potentially improve your workload from greenkeeper etc, while at worst not making your workload worse (a script that only diffs a sub-directory). Seems like it's worth a try anyway? You could make another repo maybe to give it a try for a version or two and see how it goes? Either way, I find this repo super useful, so thanks :-)

**Comment by pvinis** [comment]
Indeed I made a [test](https://github.com/pvinis/testtest) repo. Diffing a dir is fine for making a patch, but I don't know that there is away to get the `compare` view on github for a specific dir. And I want to keep that compare view.

**Comment by mikehardy** [comment]
hmmm I use that compare view also. Maybe solveable with a policy - like all non-sample-app changes are always made in tags between RN versions? That would reduce utility of compare view to only single version gaps though. May not be possible... Or maybe docs are in a non-default branch, or in a fully separate repo and they just cross-reference?

**Comment by pvinis** [comment]
Docs in a non-default branch makes it hard for people to find the links, since it would be a link to the list of links, kinda sucks.
I also thought of two repos, but that is basically the same as two branches, and probably two branches are easier to handle than two repos.
The only thing I can think of for one branch is if i find another service to do the `compare` view, and not github, so it would be a link to some diff service that would support dirs, or I keep it as is and just rely on my own build bot to do the commits, instead of greenkeeper.

Some more investigation is needed, and that's why I made this issue, so hopefully, we find a good solution. It's a very micro-optimization problem :p

**Comment by mikehardy** [comment]
> Docs in a non-default branch makes it hard for people to find the links, since it would be a link to the list of links, kinda sucks.
> I also thought of two repos, but that is basically the same as two branches, and probably two branches are easier to handle than two repos.

To me, all the above and this is the same as actually saying "two branches is not easier to handle than two repos" :-)

But this:

>  It's a very micro-optimization problem :p

...more than anything. The repo is already really really useful as is - even if for whatever reason you are having a Real Life (tm) and tags pile up, it's very easy to clone and it is reliable when you run the new version script locally to do self-service.

**Comment by pvinis** [comment]
That is true. There will never be a problem since we are purging. So running it locally on a fork will always generate exactly what is needed. Maybe I'll just leave things as they are, and just make sure I generate the commits quickly after the release of a version, and done :)

**Comment by pvinis** [comment]
I decided to use the master branch for doc, and have the project (and maybe more branches in the future) for the actual code and diffgen.
