### ISSUE TITLE
0.59.0-rc.1 is out!

### ISSUE THREAD

**Issue by ChrisEdson** [pvinis/rn-diff-purge#16]
Purge it, I beg of you

**Comment by pvinis** [comment]
I'm on the way home :) Ill do in soon! But hey, for now, you can purge it yourself! :D

Fork and from master run './newVersion 0.59.0-rc.1', and done :) you will have the diff ready in your repo in the project branch.


I'm setting up the automatic commit on every new npm release. I'll try to finish it on the weekend.

Thanks for using purge. 😎

**Comment by pvinis** [comment]
Purged ;)

On my phone, in the train, with digital ocean and blink.sh 🤣
