### ISSUE TITLE
Request: diff for 0.58.4...0.58.5

### ISSUE THREAD

**Issue by ldgarcia** [pvinis/rn-diff-purge#20]
Hi, would it be possible to add an entry to update from 0.58.4 to 0.58.5, without updating to 0.59.x first?

**Comment by ldgarcia** [comment]
Perhaps updating the Bash script to something like:

````bash

# get previous version
prevTag=${2:-$(git tag --points-at HEAD)}
prevVersion=$(basename "$prevTag")

````

So one can then run: `sh new-version.sh 0.58.5 0.58.4`

**Comment by ldgarcia** [comment]
Closing since related issue is discussed in #3

**Comment by pvinis** [comment]
;)

**Comment by pvinis** [comment]
The order shouldn't matter anyway. as long as you have 'version/before...version/after' and it exists, it will work. I am making some changes in the 'better-script' branch. Not there yet but soon.
