### ISSUE TITLE
Diff 2 specific versions e.g. 0.58.4 to 0.58.5

### ISSUE THREAD

**Issue by jpls93** [pvinis/rn-diff-purge#21]
Currently, looks like it goes from `0.58.4` to `0.59.0-rc.0`, `0.59.0-rc.1`, and `0.59.0-rc.2` before going to `0.58.5`

**Comment by pvinis** [comment]
Indeed. There is no problem with it, besides the diff from `0.58.5` to `0.59.0-rc.*`. I am working on a new table of diffs that should be soon finished. I hope before the final `0.59.0` is out.

Did you have any specific problem with the diffs?

**Comment by jpls93** [comment]
@pvinis ah, no. just curious about the format where it jumped to `0.59.x-rc.y` then back to `0.58.a` 😄

**Comment by pvinis** [comment]
Cool. Then I will close this issue. If you get into some problem, let me know. I'll try to have the grid asap. :)
