### ISSUE TITLE
Comparing branches now shows every file as new

### ISSUE THREAD

**Issue by blefebvre** [pvinis/rn-diff-purge#22]
Hi @pvinis,

First of all, I am a huge fan of this repo. Your approach has made upgrades so much simpler for me. Thank you!

I am working through an upgrade of a side project and was making good progress yesterday. When I returned to finish the last few versions today, I found that the diffs generated by Github were showing every file as new. 

Even the example listed in the README as having no changes (https://github.com/pvinis/rn-diff-purge/compare/version/0.29.0...version/0.29.2) is reporting: "Showing 38 changed files with 2,064 additions and 0 deletions." The branches look nearly identical at a glance, although it does appear that they include a commit from within the last 24 hours.

Did something happen in the last day or so that has affected the accurate generation of diffs? Or, is this an issue on Github's side?

Thanks again for all the work you put into this repo! 👍

**Comment by pvinis** [comment]
I am aware of this, and I am changing things, that should be done in a couple of days or so.

The solution for now is to remove one dot. If the link is `https://github.com/pvinis/rn-diff-purge/compare/version/0.29.0...version/0.29.2`, make it `https://github.com/pvinis/rn-diff-purge/compare/version/0.29.0..version/0.29.2` by removing one of the three buttons between the two versions.

**Comment by pvinis** [comment]
I am restructuring the way the versions compare, so we don't have problems with out-of-order releases, like `0.59.0-rc.0` before `0.58.4`. I started last weekend and I want to finish it by this weekend. It will be nicer :)

**Comment by pvinis** [comment]
Should be all fixed with the new table.
