### ISSUE TITLE
improve new-version

### ISSUE THREAD

**Issue by pvinis** [pvinis/rn-diff-purge#3]
- ~~[ ] make the script runnable like `./new-version.h`, without an arg. it should get the version from the root `package.json`.~~

- ~~[ ] also it should check if the latest version is the current version, and dont do anything in that case~~

- ~~[ ] check if i can make greenkeeper and travis work together, so that when greenkeeper fires, it should make a pr to the master, but also to the project branch. on the master, it should just update the package.json. on the project branch, it should create a pr with the changed files? or maybe just pushing directly is good enough, without the hassle of two prs, but just one on master.~~

- [ ] pull on all branches before doing any work when running the script.

Most of these are obsolete with the new grid system.

**Comment by mikehardy** [comment]
It looks there should be some logic for overlapping versions as well. For instance, the diff entries generated for 0.58.5 are overlapping with the 0.59-rc releases, and even if that is just because of the RC status on 0.59, it is conceivable that a 0.58.6 could overlap with a real 0.59.0

**Comment by pvinis** [comment]
Indeed. I am working on something like a grid. I want to change the `new-version` script to get the correct previous version, and then to make a table with the releases, and diffs for all possibilities.

**Comment by pvinis** [comment]
Done
