### ISSUE TITLE
"lint" script added?

### ISSUE THREAD

**Issue by friederbluemle** [pvinis/rn-diff-purge#32]
The [diff between 0.59.1 and 0.59.2](https://github.com/pvinis/rn-diff-purge/compare/version/0.59.1..version/0.59.2) shows that there is now a `lint` command added to the `scripts` section, plus an `eslint` dependency (and others) in `devDependencies`.

However, when I generate a default boilerplate project of `0.59.2` _today_, it *does not* contain this command/script:

    react-native init rn0592 --version 0.59.2

    

```
$ head -8 package.json
{
  "name": "rn0592",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
```

What's the reason?

I'm mentioning "_today_", because **the same exact command** executed a few days ago yielded a different project. Very concerning/confusing.

**Comment by pvinis** [comment]
good catch. I will try it as well and check it, but I have had things like that happen before. I will investigate and talk with some people in the RN team and get back to you about this.

**Comment by pvinis** [comment]
I'm back from holidays in 2 days so I'll check then.

/remind me this

**Comment by friederbluemle** [comment]
Thanks a lot @pvinis :+1:

**Comment by pvinis** [comment]
I will close this for now. If we have differences like that, it's easy enough to delete a release from this repo, by deleting the diffs for it, deleting the branch and deleting it from the `RELEASES` file. Then we can run the `new-release` script again and get the latest.

It is not the usual thing for something like that to happen, so I'll leave it as it, and if we get reports for things like that, we will fix it.

I have fix it for this case. https://github.com/react-native-community/rn-diff-purge/compare/release/0.59.1..release/0.59.2

**Comment by friederbluemle** [comment]
Thanks @pvinis - It's definitely "easy enough" to rerun and redo everything, but it's never really that nice to force push a public `master` branch, or recreate published Git tags pointing to a different commit..

It would be helpful to understand how this could have happened in the first place using the official `react-native` command **specifying a finalized RN version**. I'm sure you have more knowledge than most other people about its internal workings.

**Comment by pvinis** [comment]
Well, the thing is that when we do an `init`, a script runs to make our project. Some parts are defined, and some depend on other scripts/packages. A more extreme example is with `0.22.0`, `react` in `package.json` was just the latest. If you ran an init back then, you would get a react version that worked with 0.22.0 well. If you init with 0.22.0 today, you will get react 16.8.x, which most definitely does not work with 0.22.0. I can investigate more about this lint script, and find where it was added and removed and what exactly happened, but the idea here is that "recent" releases in relative terms (could be 2 days, could be 2 years) are correct. It might have come from the separation of cli from the main repo, and different versions of it generated a slightly different package.json.

In the long term (a later upgrade), if there is something extra or something missing like that link script, the upgrade would have conflicts, so then you as the user can decide if you want that script or not. So you see that once again, it comes down to the template upgrades being guidelines, and not hard requirements. Hence the suggestion of manual upgrading using the diff. You see what changed, you decide what you want of these changes, and you are upgraded! :)
