### ISSUE TITLE
Patch Instructions - curl command incorrect

### ISSUE THREAD

**Issue by zachrnolan** [pvinis/rn-diff-purge#8]
I noticed that the instructions for patching weren't working.

`curl https://github.com/pvinis/rn-diff-purge/compare/rn-0.29.0...rn-0.30.0.diff > upgrade-rn.patch` should actually be `curl https://github.com/pvinis/rn-diff-purge/compare/version/0.29.0...version/0.30.0.diff > upgrade-rn.patch`

**Comment by pvinis** [comment]
op. nice catch. I'll change it. thanks!

**Comment by pvinis** [comment]
fixed in a6a04d175bc29977477dd7a1634879a963f8497a
