### ISSUE TITLE
react-native upgrade to 0.58{1,2,3}

### ISSUE THREAD

**Issue by mikehardy** [pvinis/rn-diff-purge#9]
Not sure why greenkeeper didn't fire for you, but 0.58.x has revved three times. On [my local fork of this excellent project](https://github.com/mikehardy/rn-diff-purge) your new-version script did the needful exactly as expected, but as mentioned in the docs I don't believe I can usefully submit a PR?

**Comment by pvinis** [comment]
I noticed greenkeeper didn't fire, so I did it manually, but after so long it still hasn't fired. I should check for alternatives, or make a script to check or something.

For PR, I honestly have no idea. I guess it would need to be a PR for the `project` branch, and a PR for the `master`?

I'll run all of those manually right now. Thanks for the bump. I'll spend some time to try to automate this better, with or without greenkeeper.

Thanks again, for starring and "advertising" this repo! ❤️

**Comment by pvinis** [comment]
Ok, all up to date!
